name: fenwick_tree
description: A simple Fenwick Tree (also known as Binary Indexed Tree or BIT).
version: 1.0.0
homepage: https://www.github.com/modulovalue/dart_fenwick_tree
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
issue_tracker: https://github.com/modulovalue/dart_fenwick_tree/issues

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.0.0
  abstract_dart: ^1.0.1

dev_dependencies:
  extra_pedantic: ^1.1.1
  test: ^1.5.0
  test_coverage: ^0.2.0
