name: fenwick_tree
description: A simple fenwick tree in dart.
version: 0.1.0
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/dart_fenwick_tree
repository: https://github.com/modulovalue/dart_fenwick_tree
issue_tracker: https://github.com/modulovalue/dart_fenwick_tree/issues

environment:
  sdk: '>2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.7
  abstract_dart: ^0.0.3

dev_dependencies:
  test: ^1.6.6